version: '3.8'

services:
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-app
    volumes:
      - ..:/mnt
    working_dir: /mnt
    ports:
      - 8080:8080
    depends_on:
      - demo-mysql
      - demo-redis
    tty: true
