name: build

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
        - "dev"
        - "prod"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-alpine3.20
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - uses: ./.github/actions/lint
    - uses: ./.github/actions/test
    # TODO: upload to s3
    - name: Build
      run: |
        make build
        echo "option: ${{ github.event.inputs.environment }}"
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: grpc-sample
        path: ./app/grpc-sample
