name: build

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: For which environment the build artifact is.
        options:
          - "dev"
          - "prd"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-alpine3.20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      #- uses: ./.github/actions/lint
      #- uses: ./.github/actions/test
      - name: Build
        run: make build
      - name: Artifact Storage
        uses: actions/checkout@v4
        with:
          repository: takahiroaoki/artifact-storage.git
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: artifact-storage
      - name: Upload
        working-directory: artifact-storage
        run: |
          git config --local user.email ""
          git config --local user.name "GitHub Actions"
          git checkout main
          git pull
          mkdir -p ./grpc-sample/${{ github.event.inputs.environment }}
          mv -f ../app/grpc-sample ./grpc-sample/${{ github.event.inputs.environment }}
          git add .
          git commit -m ":sparkles: Build by GitHub Actions"
          git push
