name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-alpine3.20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/test
      - name: Build
        working-directory: app
        run: |
          go env -w CGO_ENABLED=0
          go env -w GOOS=linux
          go env -w GOARCH=amd64
          go build -o grpc-sample-${{ github.ref_name }}
      - name: Checkout to artifact-storage
        uses: actions/checkout@v4
        with:
          repository: takahiroaoki/artifact-storage.git
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: artifact-storage
          ref: main
      - name: Upload
        working-directory: artifact-storage
        run: |
          git config --local user.email ""
          git config --local user.name "GitHub Actions"
          mkdir -p ./grpc-sample
          mv -n ../app/grpc-sample-${{ github.ref_name }} ./grpc-sample/
          git add .
          git commit -m ":sparkles: Build by GitHub Actions"
          git push